# Generated by Django 3.0 on 2020-02-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='s',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
