# Generated by Django 3.0 on 2020-02-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200212_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='roomName',
            field=models.TextField(default=''),
        ),
    ]
