# Generated by Django 3.0 on 2019-12-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='s',
            field=models.SlugField(default='default'),
        ),
    ]
