# Generated by Django 3.0 on 2019-12-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0002_course_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='s',
            field=models.SlugField(),
        ),
    ]
