# Generated by Django 3.0 on 2019-12-21 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0003_auto_20191221_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='s',
            field=models.SlugField(unique=True),
        ),
    ]
