# Generated by Django 3.0 on 2019-12-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_lessonprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonprogress',
            options={'verbose_name_plural': 'Lesson Progression'},
        ),
        migrations.AlterField(
            model_name='lessonprogress',
            name='finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
