# Generated by Django 3.0 on 2020-01-01 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_lesson_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='s',
        ),
    ]
