# Generated by Django 3.0 on 2020-01-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_remove_lesson_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='s',
            field=models.SlugField(default='default'),
            preserve_default=False,
        ),
    ]
