# Generated by Django 3.0 on 2020-01-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_lesson_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='s',
            field=models.SlugField(unique=True),
        ),
    ]
