# Generated by Django 3.0 on 2020-01-01 16:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_auto_20200101_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='s',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
