# Generated by Django 3.0 on 2020-01-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_auto_20200101_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='s',
            field=models.SlugField(default=models.CharField(max_length=255), unique=True),
        ),
    ]
