# Generated by Django 3.0 on 2020-01-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0012_auto_20200101_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='s',
            field=models.SlugField(unique=True),
        ),
    ]
