# Generated by Django 3.0 on 2020-02-06 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_auto_20200204_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.AlterModelOptions(
            name='quizanswer',
            options={'verbose_name_plural': 'Question Answers'},
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='quizanswer',
            old_name='answer',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.QuizQuestion'),
        ),
    ]
