# Generated by Django 3.0 on 2020-02-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0022_auto_20200225_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='code',
        ),
    ]
