# Generated by Django 3.0 on 2020-02-25 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0023_remove_lesson_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='shortDesc',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
