# Generated by Django 3.0 on 2020-02-16 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
    ]
