# Generated by Django 3.0 on 2020-02-13 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='colour',
            field=models.CharField(default='red', max_length=20),
        ),
    ]
