# Generated by Django 3.0 on 2020-02-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_award_colour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophies',
            name='lesson',
        ),
        migrations.AddField(
            model_name='trophies',
            name='action',
            field=models.CharField(default='Completed', max_length=255),
        ),
    ]
